version: '3.9'

services:
  fast-api:
    container_name: fast-api
    image: fast-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - PROFILES_ACTIVE=dev
    restart: unless-stopped