version: "3"

networks:
  database-group-net:
    driver: bridge

services:
  master-database:
    image: mysql/mysql-server:5.7
    container_name: master-database
    hostname: master-database
    networks:
      - database-group-net
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33306:3306"
    volumes:
      # local:container 
      - ./data/master/config/my.cnf:/etc/mysql/my.cnf
      - ./data/master/data:/home/docker/data
    command:
      - --server-id=1
      - --log-bin=mysql-bin-1.log
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
      - --gtid-mode=ON
      - --transaction-write-set-extraction=XXHASH64
      - --binlog-checksum=NONE
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --plugin-load=group_replication.so
      - --relay-log-recovery=ON
      - --loose-group-replication-start-on-boot=OFF
      - --loose-group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      - --loose-group-replication-local-address=master-database:6606
      - --loose-group-replication-group-seeds=master-database:6606,slave-database:6606
      - --loose-group-replication-single-primary-mode=ON
      - --loose-group-replication-enforce-update-everywhere-checks=OFF

  slave-database:
    image: mysql/mysql-server:5.7
    container_name: slave-database
    hostname: slave-database
    depends_on:
      - master-database
    networks:
      - database-group-net
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33307:3306"
    volumes:
      # local:container 
      - ./data/slave/config/my.cnf:/etc/mysql/my.cnf
      - ./data/slave/data:/home/docker/data
    command:
      - --server-id=2
      - --log-bin=mysql-bin-1.log
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
      - --gtid-mode=ON
      - --transaction-write-set-extraction=XXHASH64
      - --binlog-checksum=NONE
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --plugin-load=group_replication.so
      - --relay-log-recovery=ON
      - --loose-group-replication-start-on-boot=OFF
      - --loose-group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      - --loose-group-replication-local-address=slave-database:6606
      - --loose-group-replication-group-seeds=master-database:6606,slave-database:6606
      - --loose-group-replication-single-primary-mode=ON
      - --loose-group-replication-enforce-update-everywhere-checks=OFF
      - --read-only=ON
