-- liquibase formatted sql
-- changeset trunganhvu:20241118-1
CREATE TABLE groups (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        created_time TIMESTAMP(6) WITHOUT TIME ZONE,
                        description VARCHAR(500),
                        modified_time TIMESTAMP(6) WITHOUT TIME ZONE,
                        name VARCHAR(100),
                        CONSTRAINT "groupsPK" PRIMARY KEY (id)
);

-- changeset trunganhvu:20241118-2
ALTER TABLE
    groups
    ADD
        CONSTRAINT UC_GROUPSDESCRIPTION_COL UNIQUE (description);

-- changeset trunganhvu:20241118-3
ALTER TABLE
    groups
    ADD
        CONSTRAINT UC_GROUPSNAME_COL UNIQUE (name);