-- liquibase formatted sql
-- changeset trunganhvu:20241119-3
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);
