version: '3.9'

services:
  angular-app:
    container_name: angular-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4200"
    volumes:
      # Mount source code for live development
      - ./:/usr/src/app
      # Use named volume for node_modules to prevent overwriting with host directory
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    # Keep the container running even on failure
    restart: unless-stopped

volumes:
  node_modules: